language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t olusegunf/docker-react -f Dockerfile .


script:
  - docker run -e CI=true olusegunf/docker-react npm run build

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-360680948646"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
