language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t olusegunf/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true olusegunf/docker-react npm run test

